package com.geeksville.apiproxy;

/**
 * These are low level routines called by the GCS to hook into the proxy.
 * 
 * @author kevinh
 * 
 */
public interface GCSHooks {
	/**
	 * Provide the callbacks for the GCS. GCS must call this routine before
	 * calling any other API functions.
	 * 
	 * @param cb
	 */
	void setCallback(GCSCallback cb);

	/**
	 * GCS must call this for ever mavlink packet received or sent from the
	 * vehicle
	 * 
	 * @param bytes
	 *            the packet
	 * @param fromInterface
	 *            the interface # this data arrived on (or -1 if generated by
	 *            the GCS itself)
	 */
	void filterMavlink(int fromInterface, byte[] bytes);

	/**
	 * Connect to web service
	 * 
	 * @param userName
	 * @param password
	 */
	void loginUser(String userName, String password);

	/**
	 * Associate a server vehicleId string with a particular mavlink sysId. GCS
	 * must call this for every vehicle that is connected.
	 * 
	 * @param vehicleId
	 * @param mavlinkSysId
	 */
	void setVehicleId(String vehicleId, int mavlinkSysId);
}
