// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/webapi.proto

package com.geeksville.dapi;

public final class Webapi {
  private Webapi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum EnvelopeMsgCode
      implements com.google.protobuf.ProtocolMessageEnum {
    LoginMsgCode(0, 10),
    MavlinkMsgCode(1, 11),
    ;
    
    public static final int LoginMsgCode_VALUE = 10;
    public static final int MavlinkMsgCode_VALUE = 11;
    
    
    public final int getNumber() { return value; }
    
    public static EnvelopeMsgCode valueOf(int value) {
      switch (value) {
        case 10: return LoginMsgCode;
        case 11: return MavlinkMsgCode;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<EnvelopeMsgCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EnvelopeMsgCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnvelopeMsgCode>() {
            public EnvelopeMsgCode findValueByNumber(int number) {
              return EnvelopeMsgCode.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.geeksville.dapi.Webapi.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final EnvelopeMsgCode[] VALUES = {
      LoginMsgCode, MavlinkMsgCode, 
    };
    
    public static EnvelopeMsgCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private EnvelopeMsgCode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.geeksville.dapi.EnvelopeMsgCode)
  }
  
  public interface LoginMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string username = 1;
    boolean hasUsername();
    String getUsername();
    
    // required string password = 2;
    boolean hasPassword();
    String getPassword();
  }
  public static final class LoginMsg extends
      com.google.protobuf.GeneratedMessage
      implements LoginMsgOrBuilder {
    // Use LoginMsg.newBuilder() to construct.
    private LoginMsg(Builder builder) {
      super(builder);
    }
    private LoginMsg(boolean noInit) {}
    
    private static final LoginMsg defaultInstance;
    public static LoginMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_LoginMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_LoginMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          username_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      username_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.geeksville.dapi.Webapi.LoginMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.LoginMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.geeksville.dapi.Webapi.LoginMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.LoginMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.geeksville.dapi.Webapi.LoginMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.LoginMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.geeksville.dapi.Webapi.LoginMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.geeksville.dapi.Webapi.LoginMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.geeksville.dapi.Webapi.LoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.LoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.geeksville.dapi.Webapi.LoginMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.geeksville.dapi.Webapi.LoginMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_LoginMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_LoginMsg_fieldAccessorTable;
      }
      
      // Construct using com.geeksville.dapi.Webapi.LoginMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.geeksville.dapi.Webapi.LoginMsg.getDescriptor();
      }
      
      public com.geeksville.dapi.Webapi.LoginMsg getDefaultInstanceForType() {
        return com.geeksville.dapi.Webapi.LoginMsg.getDefaultInstance();
      }
      
      public com.geeksville.dapi.Webapi.LoginMsg build() {
        com.geeksville.dapi.Webapi.LoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.geeksville.dapi.Webapi.LoginMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.geeksville.dapi.Webapi.LoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.geeksville.dapi.Webapi.LoginMsg buildPartial() {
        com.geeksville.dapi.Webapi.LoginMsg result = new com.geeksville.dapi.Webapi.LoginMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.geeksville.dapi.Webapi.LoginMsg) {
          return mergeFrom((com.geeksville.dapi.Webapi.LoginMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.geeksville.dapi.Webapi.LoginMsg other) {
        if (other == com.geeksville.dapi.Webapi.LoginMsg.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string username = 1;
      private java.lang.Object username_ = "";
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      void setUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
      }
      
      // required string password = 2;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.geeksville.dapi.LoginMsg)
    }
    
    static {
      defaultInstance = new LoginMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.geeksville.dapi.LoginMsg)
  }
  
  public interface MavlinkMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required sint32 srcInterface = 1;
    boolean hasSrcInterface();
    int getSrcInterface();
    
    // repeated bytes packets = 2;
    java.util.List<com.google.protobuf.ByteString> getPacketsList();
    int getPacketsCount();
    com.google.protobuf.ByteString getPackets(int index);
  }
  public static final class MavlinkMsg extends
      com.google.protobuf.GeneratedMessage
      implements MavlinkMsgOrBuilder {
    // Use MavlinkMsg.newBuilder() to construct.
    private MavlinkMsg(Builder builder) {
      super(builder);
    }
    private MavlinkMsg(boolean noInit) {}
    
    private static final MavlinkMsg defaultInstance;
    public static MavlinkMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public MavlinkMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_MavlinkMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_MavlinkMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required sint32 srcInterface = 1;
    public static final int SRCINTERFACE_FIELD_NUMBER = 1;
    private int srcInterface_;
    public boolean hasSrcInterface() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSrcInterface() {
      return srcInterface_;
    }
    
    // repeated bytes packets = 2;
    public static final int PACKETS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> packets_;
    public java.util.List<com.google.protobuf.ByteString>
        getPacketsList() {
      return packets_;
    }
    public int getPacketsCount() {
      return packets_.size();
    }
    public com.google.protobuf.ByteString getPackets(int index) {
      return packets_.get(index);
    }
    
    private void initFields() {
      srcInterface_ = 0;
      packets_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSrcInterface()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, srcInterface_);
      }
      for (int i = 0; i < packets_.size(); i++) {
        output.writeBytes(2, packets_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, srcInterface_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < packets_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(packets_.get(i));
        }
        size += dataSize;
        size += 1 * getPacketsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.geeksville.dapi.Webapi.MavlinkMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.MavlinkMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.geeksville.dapi.Webapi.MavlinkMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.MavlinkMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.geeksville.dapi.Webapi.MavlinkMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.MavlinkMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.geeksville.dapi.Webapi.MavlinkMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.geeksville.dapi.Webapi.MavlinkMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.geeksville.dapi.Webapi.MavlinkMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.MavlinkMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.geeksville.dapi.Webapi.MavlinkMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.geeksville.dapi.Webapi.MavlinkMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_MavlinkMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_MavlinkMsg_fieldAccessorTable;
      }
      
      // Construct using com.geeksville.dapi.Webapi.MavlinkMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        srcInterface_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        packets_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.geeksville.dapi.Webapi.MavlinkMsg.getDescriptor();
      }
      
      public com.geeksville.dapi.Webapi.MavlinkMsg getDefaultInstanceForType() {
        return com.geeksville.dapi.Webapi.MavlinkMsg.getDefaultInstance();
      }
      
      public com.geeksville.dapi.Webapi.MavlinkMsg build() {
        com.geeksville.dapi.Webapi.MavlinkMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.geeksville.dapi.Webapi.MavlinkMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.geeksville.dapi.Webapi.MavlinkMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.geeksville.dapi.Webapi.MavlinkMsg buildPartial() {
        com.geeksville.dapi.Webapi.MavlinkMsg result = new com.geeksville.dapi.Webapi.MavlinkMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.srcInterface_ = srcInterface_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          packets_ = java.util.Collections.unmodifiableList(packets_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.packets_ = packets_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.geeksville.dapi.Webapi.MavlinkMsg) {
          return mergeFrom((com.geeksville.dapi.Webapi.MavlinkMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.geeksville.dapi.Webapi.MavlinkMsg other) {
        if (other == com.geeksville.dapi.Webapi.MavlinkMsg.getDefaultInstance()) return this;
        if (other.hasSrcInterface()) {
          setSrcInterface(other.getSrcInterface());
        }
        if (!other.packets_.isEmpty()) {
          if (packets_.isEmpty()) {
            packets_ = other.packets_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePacketsIsMutable();
            packets_.addAll(other.packets_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSrcInterface()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              srcInterface_ = input.readSInt32();
              break;
            }
            case 18: {
              ensurePacketsIsMutable();
              packets_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required sint32 srcInterface = 1;
      private int srcInterface_ ;
      public boolean hasSrcInterface() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSrcInterface() {
        return srcInterface_;
      }
      public Builder setSrcInterface(int value) {
        bitField0_ |= 0x00000001;
        srcInterface_ = value;
        onChanged();
        return this;
      }
      public Builder clearSrcInterface() {
        bitField0_ = (bitField0_ & ~0x00000001);
        srcInterface_ = 0;
        onChanged();
        return this;
      }
      
      // repeated bytes packets = 2;
      private java.util.List<com.google.protobuf.ByteString> packets_ = java.util.Collections.emptyList();;
      private void ensurePacketsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          packets_ = new java.util.ArrayList<com.google.protobuf.ByteString>(packets_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getPacketsList() {
        return java.util.Collections.unmodifiableList(packets_);
      }
      public int getPacketsCount() {
        return packets_.size();
      }
      public com.google.protobuf.ByteString getPackets(int index) {
        return packets_.get(index);
      }
      public Builder setPackets(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePacketsIsMutable();
        packets_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addPackets(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePacketsIsMutable();
        packets_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllPackets(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensurePacketsIsMutable();
        super.addAll(values, packets_);
        onChanged();
        return this;
      }
      public Builder clearPackets() {
        packets_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.geeksville.dapi.MavlinkMsg)
    }
    
    static {
      defaultInstance = new MavlinkMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.geeksville.dapi.MavlinkMsg)
  }
  
  public interface EnvelopeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.geeksville.dapi.EnvelopeMsgCode type = 3;
    boolean hasType();
    com.geeksville.dapi.Webapi.EnvelopeMsgCode getType();
    
    // optional .com.geeksville.dapi.LoginMsg heartbeat = 10;
    boolean hasHeartbeat();
    com.geeksville.dapi.Webapi.LoginMsg getHeartbeat();
    com.geeksville.dapi.Webapi.LoginMsgOrBuilder getHeartbeatOrBuilder();
    
    // optional .com.geeksville.dapi.MavlinkMsg mavlink = 11;
    boolean hasMavlink();
    com.geeksville.dapi.Webapi.MavlinkMsg getMavlink();
    com.geeksville.dapi.Webapi.MavlinkMsgOrBuilder getMavlinkOrBuilder();
  }
  public static final class Envelope extends
      com.google.protobuf.GeneratedMessage
      implements EnvelopeOrBuilder {
    // Use Envelope.newBuilder() to construct.
    private Envelope(Builder builder) {
      super(builder);
    }
    private Envelope(boolean noInit) {}
    
    private static final Envelope defaultInstance;
    public static Envelope getDefaultInstance() {
      return defaultInstance;
    }
    
    public Envelope getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_Envelope_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_Envelope_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .com.geeksville.dapi.EnvelopeMsgCode type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private com.geeksville.dapi.Webapi.EnvelopeMsgCode type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.geeksville.dapi.Webapi.EnvelopeMsgCode getType() {
      return type_;
    }
    
    // optional .com.geeksville.dapi.LoginMsg heartbeat = 10;
    public static final int HEARTBEAT_FIELD_NUMBER = 10;
    private com.geeksville.dapi.Webapi.LoginMsg heartbeat_;
    public boolean hasHeartbeat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.geeksville.dapi.Webapi.LoginMsg getHeartbeat() {
      return heartbeat_;
    }
    public com.geeksville.dapi.Webapi.LoginMsgOrBuilder getHeartbeatOrBuilder() {
      return heartbeat_;
    }
    
    // optional .com.geeksville.dapi.MavlinkMsg mavlink = 11;
    public static final int MAVLINK_FIELD_NUMBER = 11;
    private com.geeksville.dapi.Webapi.MavlinkMsg mavlink_;
    public boolean hasMavlink() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.geeksville.dapi.Webapi.MavlinkMsg getMavlink() {
      return mavlink_;
    }
    public com.geeksville.dapi.Webapi.MavlinkMsgOrBuilder getMavlinkOrBuilder() {
      return mavlink_;
    }
    
    private void initFields() {
      type_ = com.geeksville.dapi.Webapi.EnvelopeMsgCode.LoginMsgCode;
      heartbeat_ = com.geeksville.dapi.Webapi.LoginMsg.getDefaultInstance();
      mavlink_ = com.geeksville.dapi.Webapi.MavlinkMsg.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasHeartbeat()) {
        if (!getHeartbeat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMavlink()) {
        if (!getMavlink().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(10, heartbeat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(11, mavlink_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, heartbeat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, mavlink_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.geeksville.dapi.Webapi.Envelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.Envelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.geeksville.dapi.Webapi.Envelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.Envelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.geeksville.dapi.Webapi.Envelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.Envelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.geeksville.dapi.Webapi.Envelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.geeksville.dapi.Webapi.Envelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.geeksville.dapi.Webapi.Envelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.geeksville.dapi.Webapi.Envelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.geeksville.dapi.Webapi.Envelope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.geeksville.dapi.Webapi.EnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_Envelope_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.geeksville.dapi.Webapi.internal_static_com_geeksville_dapi_Envelope_fieldAccessorTable;
      }
      
      // Construct using com.geeksville.dapi.Webapi.Envelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeartbeatFieldBuilder();
          getMavlinkFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.geeksville.dapi.Webapi.EnvelopeMsgCode.LoginMsgCode;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (heartbeatBuilder_ == null) {
          heartbeat_ = com.geeksville.dapi.Webapi.LoginMsg.getDefaultInstance();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (mavlinkBuilder_ == null) {
          mavlink_ = com.geeksville.dapi.Webapi.MavlinkMsg.getDefaultInstance();
        } else {
          mavlinkBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.geeksville.dapi.Webapi.Envelope.getDescriptor();
      }
      
      public com.geeksville.dapi.Webapi.Envelope getDefaultInstanceForType() {
        return com.geeksville.dapi.Webapi.Envelope.getDefaultInstance();
      }
      
      public com.geeksville.dapi.Webapi.Envelope build() {
        com.geeksville.dapi.Webapi.Envelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.geeksville.dapi.Webapi.Envelope buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.geeksville.dapi.Webapi.Envelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.geeksville.dapi.Webapi.Envelope buildPartial() {
        com.geeksville.dapi.Webapi.Envelope result = new com.geeksville.dapi.Webapi.Envelope(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (heartbeatBuilder_ == null) {
          result.heartbeat_ = heartbeat_;
        } else {
          result.heartbeat_ = heartbeatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (mavlinkBuilder_ == null) {
          result.mavlink_ = mavlink_;
        } else {
          result.mavlink_ = mavlinkBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.geeksville.dapi.Webapi.Envelope) {
          return mergeFrom((com.geeksville.dapi.Webapi.Envelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.geeksville.dapi.Webapi.Envelope other) {
        if (other == com.geeksville.dapi.Webapi.Envelope.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasHeartbeat()) {
          mergeHeartbeat(other.getHeartbeat());
        }
        if (other.hasMavlink()) {
          mergeMavlink(other.getMavlink());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasHeartbeat()) {
          if (!getHeartbeat().isInitialized()) {
            
            return false;
          }
        }
        if (hasMavlink()) {
          if (!getMavlink().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.geeksville.dapi.Webapi.EnvelopeMsgCode value = com.geeksville.dapi.Webapi.EnvelopeMsgCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 82: {
              com.geeksville.dapi.Webapi.LoginMsg.Builder subBuilder = com.geeksville.dapi.Webapi.LoginMsg.newBuilder();
              if (hasHeartbeat()) {
                subBuilder.mergeFrom(getHeartbeat());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeartbeat(subBuilder.buildPartial());
              break;
            }
            case 90: {
              com.geeksville.dapi.Webapi.MavlinkMsg.Builder subBuilder = com.geeksville.dapi.Webapi.MavlinkMsg.newBuilder();
              if (hasMavlink()) {
                subBuilder.mergeFrom(getMavlink());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMavlink(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.geeksville.dapi.EnvelopeMsgCode type = 3;
      private com.geeksville.dapi.Webapi.EnvelopeMsgCode type_ = com.geeksville.dapi.Webapi.EnvelopeMsgCode.LoginMsgCode;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.geeksville.dapi.Webapi.EnvelopeMsgCode getType() {
        return type_;
      }
      public Builder setType(com.geeksville.dapi.Webapi.EnvelopeMsgCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.geeksville.dapi.Webapi.EnvelopeMsgCode.LoginMsgCode;
        onChanged();
        return this;
      }
      
      // optional .com.geeksville.dapi.LoginMsg heartbeat = 10;
      private com.geeksville.dapi.Webapi.LoginMsg heartbeat_ = com.geeksville.dapi.Webapi.LoginMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.geeksville.dapi.Webapi.LoginMsg, com.geeksville.dapi.Webapi.LoginMsg.Builder, com.geeksville.dapi.Webapi.LoginMsgOrBuilder> heartbeatBuilder_;
      public boolean hasHeartbeat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.geeksville.dapi.Webapi.LoginMsg getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          return heartbeat_;
        } else {
          return heartbeatBuilder_.getMessage();
        }
      }
      public Builder setHeartbeat(com.geeksville.dapi.Webapi.LoginMsg value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartbeat_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setHeartbeat(
          com.geeksville.dapi.Webapi.LoginMsg.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeHeartbeat(com.geeksville.dapi.Webapi.LoginMsg value) {
        if (heartbeatBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              heartbeat_ != com.geeksville.dapi.Webapi.LoginMsg.getDefaultInstance()) {
            heartbeat_ =
              com.geeksville.dapi.Webapi.LoginMsg.newBuilder(heartbeat_).mergeFrom(value).buildPartial();
          } else {
            heartbeat_ = value;
          }
          onChanged();
        } else {
          heartbeatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = com.geeksville.dapi.Webapi.LoginMsg.getDefaultInstance();
          onChanged();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.geeksville.dapi.Webapi.LoginMsg.Builder getHeartbeatBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHeartbeatFieldBuilder().getBuilder();
      }
      public com.geeksville.dapi.Webapi.LoginMsgOrBuilder getHeartbeatOrBuilder() {
        if (heartbeatBuilder_ != null) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          return heartbeat_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.geeksville.dapi.Webapi.LoginMsg, com.geeksville.dapi.Webapi.LoginMsg.Builder, com.geeksville.dapi.Webapi.LoginMsgOrBuilder> 
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.geeksville.dapi.Webapi.LoginMsg, com.geeksville.dapi.Webapi.LoginMsg.Builder, com.geeksville.dapi.Webapi.LoginMsgOrBuilder>(
                  heartbeat_,
                  getParentForChildren(),
                  isClean());
          heartbeat_ = null;
        }
        return heartbeatBuilder_;
      }
      
      // optional .com.geeksville.dapi.MavlinkMsg mavlink = 11;
      private com.geeksville.dapi.Webapi.MavlinkMsg mavlink_ = com.geeksville.dapi.Webapi.MavlinkMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.geeksville.dapi.Webapi.MavlinkMsg, com.geeksville.dapi.Webapi.MavlinkMsg.Builder, com.geeksville.dapi.Webapi.MavlinkMsgOrBuilder> mavlinkBuilder_;
      public boolean hasMavlink() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.geeksville.dapi.Webapi.MavlinkMsg getMavlink() {
        if (mavlinkBuilder_ == null) {
          return mavlink_;
        } else {
          return mavlinkBuilder_.getMessage();
        }
      }
      public Builder setMavlink(com.geeksville.dapi.Webapi.MavlinkMsg value) {
        if (mavlinkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mavlink_ = value;
          onChanged();
        } else {
          mavlinkBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setMavlink(
          com.geeksville.dapi.Webapi.MavlinkMsg.Builder builderForValue) {
        if (mavlinkBuilder_ == null) {
          mavlink_ = builderForValue.build();
          onChanged();
        } else {
          mavlinkBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeMavlink(com.geeksville.dapi.Webapi.MavlinkMsg value) {
        if (mavlinkBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              mavlink_ != com.geeksville.dapi.Webapi.MavlinkMsg.getDefaultInstance()) {
            mavlink_ =
              com.geeksville.dapi.Webapi.MavlinkMsg.newBuilder(mavlink_).mergeFrom(value).buildPartial();
          } else {
            mavlink_ = value;
          }
          onChanged();
        } else {
          mavlinkBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearMavlink() {
        if (mavlinkBuilder_ == null) {
          mavlink_ = com.geeksville.dapi.Webapi.MavlinkMsg.getDefaultInstance();
          onChanged();
        } else {
          mavlinkBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.geeksville.dapi.Webapi.MavlinkMsg.Builder getMavlinkBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMavlinkFieldBuilder().getBuilder();
      }
      public com.geeksville.dapi.Webapi.MavlinkMsgOrBuilder getMavlinkOrBuilder() {
        if (mavlinkBuilder_ != null) {
          return mavlinkBuilder_.getMessageOrBuilder();
        } else {
          return mavlink_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.geeksville.dapi.Webapi.MavlinkMsg, com.geeksville.dapi.Webapi.MavlinkMsg.Builder, com.geeksville.dapi.Webapi.MavlinkMsgOrBuilder> 
          getMavlinkFieldBuilder() {
        if (mavlinkBuilder_ == null) {
          mavlinkBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.geeksville.dapi.Webapi.MavlinkMsg, com.geeksville.dapi.Webapi.MavlinkMsg.Builder, com.geeksville.dapi.Webapi.MavlinkMsgOrBuilder>(
                  mavlink_,
                  getParentForChildren(),
                  isClean());
          mavlink_ = null;
        }
        return mavlinkBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.geeksville.dapi.Envelope)
    }
    
    static {
      defaultInstance = new Envelope(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.geeksville.dapi.Envelope)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_geeksville_dapi_LoginMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_geeksville_dapi_LoginMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_geeksville_dapi_MavlinkMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_geeksville_dapi_MavlinkMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_geeksville_dapi_Envelope_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_geeksville_dapi_Envelope_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/protobuf/webapi.proto\022\023com.ge" +
      "eksville.dapi\".\n\010LoginMsg\022\020\n\010username\030\001 " +
      "\002(\t\022\020\n\010password\030\002 \002(\t\"3\n\nMavlinkMsg\022\024\n\014s" +
      "rcInterface\030\001 \002(\021\022\017\n\007packets\030\002 \003(\014\"\242\001\n\010E" +
      "nvelope\0222\n\004type\030\003 \002(\0162$.com.geeksville.d" +
      "api.EnvelopeMsgCode\0220\n\theartbeat\030\n \001(\0132\035" +
      ".com.geeksville.dapi.LoginMsg\0220\n\007mavlink" +
      "\030\013 \001(\0132\037.com.geeksville.dapi.MavlinkMsg*" +
      "7\n\017EnvelopeMsgCode\022\020\n\014LoginMsgCode\020\n\022\022\n\016" +
      "MavlinkMsgCode\020\013B\025\n\023com.geeksville.dapi"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_geeksville_dapi_LoginMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_geeksville_dapi_LoginMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_geeksville_dapi_LoginMsg_descriptor,
              new java.lang.String[] { "Username", "Password", },
              com.geeksville.dapi.Webapi.LoginMsg.class,
              com.geeksville.dapi.Webapi.LoginMsg.Builder.class);
          internal_static_com_geeksville_dapi_MavlinkMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_geeksville_dapi_MavlinkMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_geeksville_dapi_MavlinkMsg_descriptor,
              new java.lang.String[] { "SrcInterface", "Packets", },
              com.geeksville.dapi.Webapi.MavlinkMsg.class,
              com.geeksville.dapi.Webapi.MavlinkMsg.Builder.class);
          internal_static_com_geeksville_dapi_Envelope_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_geeksville_dapi_Envelope_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_geeksville_dapi_Envelope_descriptor,
              new java.lang.String[] { "Type", "Heartbeat", "Mavlink", },
              com.geeksville.dapi.Webapi.Envelope.class,
              com.geeksville.dapi.Webapi.Envelope.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
